name: green_route
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # --- Core UI ---
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  share_plus: ^7.2.0

  # --- Firebase ---
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_secure_storage: ^9.1.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3
  flutter_tts: ^3.8.0
  firebase_storage: ^12.4.10

  # --- Maps & Location ---
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^14.0.2
  flutter_google_places_sdk: 0.4.2+1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  flutter_compass: ^0.8.0
  intl: ^0.18.0

  # --- Networking ---
  http: ^1.2.1
  rename_app: ^1.6.5

# --- Image handling ---
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/logo3.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
